version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build: .
    container_name: my_node_app
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    command: sh -c "node utils/seed.js && npm start"

volumes:
  mongo_data: